apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        discord_webhook: "{{ .discord_webhook }}/slack"
  data:
  - secretKey: discord_webhook
    remoteRef:
      key: proxmox
      property: alertmanager_discord_webhook
