apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.11.110
    path: /mnt/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Prevent binding to default local-path
  resources:
    requests:
      storage: 2Ti
  volumeName: media-nfs-pv
